/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package practica2;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sanci
 */
public class Historial extends javax.swing.JFrame {

    /**
     * Creates new form Historial
     */
    ArrayList<Pedido> pedidoaux;
    ArrayList<Pedido> unido=  new ArrayList<Pedido>();
    ArrayList<Pedido> aux =  new ArrayList<Pedido>();
    Binario binario;
    gaurdarDatos guarda;
    public Historial(ArrayList<Pedido> ped) {
        this.pedidoaux = ped;
        initComponents();
        cargarAutomatica();
        this.binario = new Binario();
        
        cargar();
    }
    
    
    public void cargarAutomatica() {
        DefaultTableModel modelo = new DefaultTableModel();

        ArrayList<Object> nombrecolumna = new ArrayList<Object>();
        nombrecolumna.add("Vehiculo");
        nombrecolumna.add("Distancia");
        nombrecolumna.add("Monto");
        nombrecolumna.add("Fecha y hora creación");
        nombrecolumna.add("decha y hora entrefa");
        for (Object columna : nombrecolumna) {
            modelo.addColumn(columna);
        }
        int fila = tabla1.getRowCount();

        this.tabla1.setModel(modelo);
        ArrayList<Object[]> datos = new ArrayList<Object[]>();
        System.out.println(pedidoaux.size());
        for (int i = 0; i < pedidoaux.size(); i++) {
            String Vehiculo = (pedidoaux.get(i).getVehiculo());
            String Distancia = (pedidoaux.get(i).getDistancia()+ " Km");
            String Monto= "Q"+(pedidoaux.get(i).getMonto());
            String FechaInicio = (pedidoaux.get(i).getFecha_creacion());
            String FechaFin = (pedidoaux.get(i).getFecha_entrega());
            datos.add(new Object[]{Vehiculo, Distancia, Monto, FechaInicio, FechaFin});
            System.out.println(datos);

        }

        for (Object[] Maestros : datos) {
            modelo.addRow(Maestros);
        }
        tabla1.setModel(modelo);

    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabla1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabla1);

        jButton1.setText("Regresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Guardar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 651, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(296, 296, 296)
                        .addComponent(jButton1)
                        .addGap(107, 107, 107)
                        .addComponent(jButton2)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ventanas ven = new ventanas();
        ven.preparacion(pedidoaux);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       guarda = new gaurdarDatos(pedidoaux);
        boolean ok = binario.guardar(guarda);
        if (ok) {
            JOptionPane.showMessageDialog(null, "Se guardaron los datos");
        } else {
            JOptionPane.showMessageDialog(null, "Ocurrio un error, no se guardaron los datos");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    public void unir(){
        
        unido.addAll(aux);
        unido.addAll(pedidoaux);
        pedidoaux = unido;
    
    }
    
    public void cargar(){
        if (binario.obtener() == null) {
            JOptionPane.showMessageDialog(null, "No hay datos");
        } else {
            guarda = binario.obtener();
            aux = guarda.ped;
            

            JOptionPane.showMessageDialog(null, "Datos cargados");
            unir();
            cargarAutomatica();
            
        }
    
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla1;
    // End of variables declaration//GEN-END:variables
}
