/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package practica2;

import java.time.LocalDateTime;
import java.util.ArrayList;
import javax.swing.JLabel;

/**
 *
 * @author sanci
 */
public class Trayectoria extends javax.swing.JFrame {

    /**
     * Creates new form Trayectoria
     */
    ArrayList<Pedido> pedidoaux;
    int moto1, moto2, moto3, indice;

    public Trayectoria(ArrayList<Pedido> ped) {
        this.pedidoaux = ped;
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Carreras de autos");

        String vei = String.valueOf(buscar("Moto1"));
        ditancia1.setText("Distancia: " + vei);
        
        String vei2 = String.valueOf(buscar("Moto2"));
        distancia2.setText("Distancia: " + vei2);
        
        String vei3 = String.valueOf(buscar("Moto3"));
        distancia3.setText("Distancia: " + vei3);
    }

    public int buscar(String vehiculo) {
        int distancia = 0;
        int indice = 0;
        for (int i = 0; i < pedidoaux.size(); i++) {
            String vehi = pedidoaux.get(i).getVehiculo();
            boolean dd = pedidoaux.get(i).isLlegado();
            if (vehiculo == vehi && dd == false) {
                System.out.println("aaaaaa");
                distancia = Integer.parseInt(pedidoaux.get(i).getDistancia());
                indice = i;
                //pedidoaux.get(i).setLlegado(true);
                break;
            }
        }
        return distancia;

    }

    public JLabel getPrimerMoto() {

        return primermoto;

    }

    public JLabel getSegundaMoto() {

        return segundamoto;

    }

    public JLabel getTercerMoto() {

        return tercerMoto;

    }

    public JLabel getBarrera() {

        return Barrera;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        primermoto = new javax.swing.JLabel();
        segundamoto = new javax.swing.JLabel();
        tercerMoto = new javax.swing.JLabel();
        Barrera = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        ditancia1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        distancia2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        distancia3 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        jLabel1.setText("Pedidos");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        primermoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/2606303.png"))); // NOI18N

        segundamoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/2606303.png"))); // NOI18N

        tercerMoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/2606303.png"))); // NOI18N

        Barrera.setBackground(new java.awt.Color(255, 102, 102));
        Barrera.setText("jLabel5");
        Barrera.setOpaque(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tercerMoto)
                    .addComponent(segundamoto)
                    .addComponent(primermoto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 574, Short.MAX_VALUE)
                .addComponent(Barrera, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Barrera, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(primermoto, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(segundamoto, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67)
                        .addComponent(tercerMoto, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jButton1.setText("Enviar Todos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Motocicleta: 1");

        ditancia1.setText("Distancia:");

        jButton2.setText("Enviar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel4.setText("Motocicleta: 2");

        distancia2.setText("Distancia:");

        jButton3.setText("Enviar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel6.setText("Motocicleta: 3");

        distancia3.setText("Distancia:");

        jButton4.setText("Enviar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Regresar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(ditancia1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(distancia2)
                    .addComponent(jButton3))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(distancia3)
                    .addComponent(jButton4))
                .addGap(41, 41, 41)
                .addComponent(jLabel1)
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jButton5))
                .addGap(83, 83, 83))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(distancia2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addComponent(jButton1))
                                    .addGroup(layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ditancia1)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton2))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton5))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(distancia3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton4))
                                    .addComponent(jLabel1))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        
        jButton2ActionPerformed(evt);
        jButton3ActionPerformed(evt);
        jButton4ActionPerformed(evt);


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        primermoto.setLocation(0, primermoto.getLocation().y);
        boolean aux = false;

        int distancia = buscar("Moto1");
        System.out.println(distancia);
        int detener = distancia * 100;
        System.out.println(detener);
        System.out.println("aa");
        Trayecto moto1 = new Trayecto(primermoto, this, detener);

        moto1.start();

        moto1.setFecha(true);
        if (moto1.isFecha() == true) {
            int indice = Trayectoriae("Moto1");
            LocalDateTime fechaHoraActual = LocalDateTime.now();
            String fecha_entrega = (String) fechaHoraActual.toString();
            pedidoaux.get(indice).setFecha_entrega(fecha_entrega);
            System.out.println(pedidoaux.get(indice).getFecha_entrega() + " aa");
            pedidoaux.get(indice).setLlegado(true);
            System.out.println("carlos");

        }

    }//GEN-LAST:event_jButton2ActionPerformed

    public int Trayectoriae(String vehiculo) {
        int aa = 0;
        for (int i = 0; i < pedidoaux.size(); i++) {
            if (pedidoaux.get(i).getVehiculo() == vehiculo) {
                aa = i;
                break;

            }
        }

        return aa;

    }
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        segundamoto.setLocation(0, segundamoto.getLocation().y);

        boolean aux = false;

        int distancia = buscar("Moto2");

        int detener = distancia * 100;
        System.out.println(detener);

        Trayecto2 moto2 = new Trayecto2(segundamoto, this, detener);

        moto2.start();

        moto2.setFecha(true);
        if (moto2.isFecha() == true) {
            int indice = Trayectoriae("Moto2");
            LocalDateTime fechaHoraActual = LocalDateTime.now();
            String fecha_entrega = (String) fechaHoraActual.toString();
            pedidoaux.get(indice).setFecha_entrega(fecha_entrega);
            System.out.println(pedidoaux.get(indice).getFecha_entrega() + " aa");
            pedidoaux.get(indice).setLlegado(true);
            System.out.println("carlos");

        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        tercerMoto.setLocation(0, tercerMoto.getLocation().y);

        

        boolean aux = false;

        int distancia = buscar("Moto3");
        int detener = distancia * 100;
        System.out.println(detener);
        Trayecto3 moto3 = new Trayecto3(tercerMoto, this, detener);
        moto3.start();

        moto3.setFecha(true);
        if (moto3.isFecha() == true) {
            int indice = Trayectoriae("Moto3");
            LocalDateTime fechaHoraActual = LocalDateTime.now();
            String fecha_entrega = (String) fechaHoraActual.toString();
            pedidoaux.get(indice).setFecha_entrega(fecha_entrega);
            pedidoaux.get(indice).setLlegado(true);

        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        ventanas ven = new ventanas();
        ven.preparacion(pedidoaux);
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Barrera;
    private javax.swing.JLabel distancia2;
    private javax.swing.JLabel distancia3;
    private javax.swing.JLabel ditancia1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel primermoto;
    private javax.swing.JLabel segundamoto;
    private javax.swing.JLabel tercerMoto;
    // End of variables declaration//GEN-END:variables
}
